version: '3'
services:
  redis:
    image: redis
    container_name: cache
    ports:
      - 6379:6379

  node-app:
    build: ./
    ports:
      - 8081:3000
    environment:
      - REDIS_URL=redis

#redis://cache
