apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.appName }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{ .Values.ingress.hostName }} 
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Values.appName }}
              servicePort: {{ .Values.service.port }}
